// Full ISO 4217 active currency list for the searchable currency picker.
// `sym` is the common sign where one exists, else ''. Display formatting for
// amounts stays in currency.js (CUR_SYM covers the frequently-used subset;
// fmtMoney/fmtCompact fall back to "CODE " for the rest).

export const CURRENCIES = [
  { code: 'AED', name: 'UAE Dirham', sym: 'د.إ' },
  { code: 'AFN', name: 'Afghan Afghani', sym: '؋' },
  { code: 'ALL', name: 'Albanian Lek', sym: 'L' },
  { code: 'AMD', name: 'Armenian Dram', sym: '֏' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', sym: 'ƒ' },
  { code: 'AOA', name: 'Angolan Kwanza', sym: 'Kz' },
  { code: 'ARS', name: 'Argentine Peso', sym: '$' },
  { code: 'AUD', name: 'Australian Dollar', sym: 'A$' },
  { code: 'AWG', name: 'Aruban Florin', sym: 'ƒ' },
  { code: 'AZN', name: 'Azerbaijani Manat', sym: '₼' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', sym: 'KM' },
  { code: 'BBD', name: 'Barbadian Dollar', sym: '$' },
  { code: 'BDT', name: 'Bangladeshi Taka', sym: '৳' },
  { code: 'BGN', name: 'Bulgarian Lev', sym: 'лв' },
  { code: 'BHD', name: 'Bahraini Dinar', sym: '.د.ب' },
  { code: 'BIF', name: 'Burundian Franc', sym: 'FBu' },
  { code: 'BMD', name: 'Bermudian Dollar', sym: '$' },
  { code: 'BND', name: 'Brunei Dollar', sym: '$' },
  { code: 'BOB', name: 'Bolivian Boliviano', sym: 'Bs.' },
  { code: 'BRL', name: 'Brazilian Real', sym: 'R$' },
  { code: 'BSD', name: 'Bahamian Dollar', sym: '$' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', sym: 'Nu.' },
  { code: 'BWP', name: 'Botswana Pula', sym: 'P' },
  { code: 'BYN', name: 'Belarusian Ruble', sym: 'Br' },
  { code: 'BZD', name: 'Belize Dollar', sym: 'BZ$' },
  { code: 'CAD', name: 'Canadian Dollar', sym: 'C$' },
  { code: 'CDF', name: 'Congolese Franc', sym: 'FC' },
  { code: 'CHF', name: 'Swiss Franc', sym: 'CHF' },
  { code: 'CLP', name: 'Chilean Peso', sym: '$' },
  { code: 'CNY', name: 'Chinese Yuan Renminbi', sym: '¥' },
  { code: 'COP', name: 'Colombian Peso', sym: '$' },
  { code: 'CRC', name: 'Costa Rican Colón', sym: '₡' },
  { code: 'CUP', name: 'Cuban Peso', sym: '$' },
  { code: 'CVE', name: 'Cape Verdean Escudo', sym: '$' },
  { code: 'CZK', name: 'Czech Koruna', sym: 'Kč' },
  { code: 'DJF', name: 'Djiboutian Franc', sym: 'Fdj' },
  { code: 'DKK', name: 'Danish Krone', sym: 'kr' },
  { code: 'DOP', name: 'Dominican Peso', sym: 'RD$' },
  { code: 'DZD', name: 'Algerian Dinar', sym: 'دج' },
  { code: 'EGP', name: 'Egyptian Pound', sym: 'E£' },
  { code: 'ERN', name: 'Eritrean Nakfa', sym: 'Nfk' },
  { code: 'ETB', name: 'Ethiopian Birr', sym: 'Br' },
  { code: 'EUR', name: 'Euro', sym: '€' },
  { code: 'FJD', name: 'Fijian Dollar', sym: 'FJ$' },
  { code: 'FKP', name: 'Falkland Islands Pound', sym: '£' },
  { code: 'GBP', name: 'British Pound Sterling', sym: '£' },
  { code: 'GEL', name: 'Georgian Lari', sym: '₾' },
  { code: 'GHS', name: 'Ghanaian Cedi', sym: 'GH₵' },
  { code: 'GIP', name: 'Gibraltar Pound', sym: '£' },
  { code: 'GMD', name: 'Gambian Dalasi', sym: 'D' },
  { code: 'GNF', name: 'Guinean Franc', sym: 'FG' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', sym: 'Q' },
  { code: 'GYD', name: 'Guyanese Dollar', sym: 'G$' },
  { code: 'HKD', name: 'Hong Kong Dollar', sym: 'HK$' },
  { code: 'HNL', name: 'Honduran Lempira', sym: 'L' },
  { code: 'HTG', name: 'Haitian Gourde', sym: 'G' },
  { code: 'HUF', name: 'Hungarian Forint', sym: 'Ft' },
  { code: 'IDR', name: 'Indonesian Rupiah', sym: 'Rp' },
  { code: 'ILS', name: 'Israeli New Shekel', sym: '₪' },
  { code: 'INR', name: 'Indian Rupee', sym: '₹' },
  { code: 'IQD', name: 'Iraqi Dinar', sym: 'ع.د' },
  { code: 'IRR', name: 'Iranian Rial', sym: '﷼' },
  { code: 'ISK', name: 'Icelandic Króna', sym: 'kr' },
  { code: 'JMD', name: 'Jamaican Dollar', sym: 'J$' },
  { code: 'JOD', name: 'Jordanian Dinar', sym: 'د.ا' },
  { code: 'JPY', name: 'Japanese Yen', sym: '¥' },
  { code: 'KES', name: 'Kenyan Shilling', sym: 'KSh' },
  { code: 'KGS', name: 'Kyrgyzstani Som', sym: 'с' },
  { code: 'KHR', name: 'Cambodian Riel', sym: '៛' },
  { code: 'KMF', name: 'Comorian Franc', sym: 'CF' },
  { code: 'KPW', name: 'North Korean Won', sym: '₩' },
  { code: 'KRW', name: 'South Korean Won', sym: '₩' },
  { code: 'KWD', name: 'Kuwaiti Dinar', sym: 'د.ك' },
  { code: 'KYD', name: 'Cayman Islands Dollar', sym: '$' },
  { code: 'KZT', name: 'Kazakhstani Tenge', sym: '₸' },
  { code: 'LAK', name: 'Lao Kip', sym: '₭' },
  { code: 'LBP', name: 'Lebanese Pound', sym: 'ل.ل' },
  { code: 'LKR', name: 'Sri Lankan Rupee', sym: 'Rs' },
  { code: 'LRD', name: 'Liberian Dollar', sym: 'L$' },
  { code: 'LSL', name: 'Lesotho Loti', sym: 'L' },
  { code: 'LYD', name: 'Libyan Dinar', sym: 'ل.د' },
  { code: 'MAD', name: 'Moroccan Dirham', sym: 'د.م.' },
  { code: 'MDL', name: 'Moldovan Leu', sym: 'L' },
  { code: 'MGA', name: 'Malagasy Ariary', sym: 'Ar' },
  { code: 'MKD', name: 'Macedonian Denar', sym: 'ден' },
  { code: 'MMK', name: 'Myanmar Kyat', sym: 'K' },
  { code: 'MNT', name: 'Mongolian Tögrög', sym: '₮' },
  { code: 'MOP', name: 'Macanese Pataca', sym: 'MOP$' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', sym: 'UM' },
  { code: 'MUR', name: 'Mauritian Rupee', sym: '₨' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', sym: 'Rf' },
  { code: 'MWK', name: 'Malawian Kwacha', sym: 'MK' },
  { code: 'MXN', name: 'Mexican Peso', sym: 'Mex$' },
  { code: 'MYR', name: 'Malaysian Ringgit', sym: 'RM' },
  { code: 'MZN', name: 'Mozambican Metical', sym: 'MT' },
  { code: 'NAD', name: 'Namibian Dollar', sym: 'N$' },
  { code: 'NGN', name: 'Nigerian Naira', sym: '₦' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', sym: 'C$' },
  { code: 'NOK', name: 'Norwegian Krone', sym: 'kr' },
  { code: 'NPR', name: 'Nepalese Rupee', sym: 'रू' },
  { code: 'NZD', name: 'New Zealand Dollar', sym: 'NZ$' },
  { code: 'OMR', name: 'Omani Rial', sym: 'ر.ع.' },
  { code: 'PAB', name: 'Panamanian Balboa', sym: 'B/.' },
  { code: 'PEN', name: 'Peruvian Sol', sym: 'S/' },
  { code: 'PGK', name: 'Papua New Guinean Kina', sym: 'K' },
  { code: 'PHP', name: 'Philippine Peso', sym: '₱' },
  { code: 'PKR', name: 'Pakistani Rupee', sym: '₨' },
  { code: 'PLN', name: 'Polish Złoty', sym: 'zł' },
  { code: 'PYG', name: 'Paraguayan Guaraní', sym: '₲' },
  { code: 'QAR', name: 'Qatari Riyal', sym: 'ر.ق' },
  { code: 'RON', name: 'Romanian Leu', sym: 'lei' },
  { code: 'RSD', name: 'Serbian Dinar', sym: 'дин' },
  { code: 'RUB', name: 'Russian Ruble', sym: '₽' },
  { code: 'RWF', name: 'Rwandan Franc', sym: 'FRw' },
  { code: 'SAR', name: 'Saudi Riyal', sym: 'ر.س' },
  { code: 'SBD', name: 'Solomon Islands Dollar', sym: 'SI$' },
  { code: 'SCR', name: 'Seychellois Rupee', sym: '₨' },
  { code: 'SDG', name: 'Sudanese Pound', sym: 'ج.س.' },
  { code: 'SEK', name: 'Swedish Krona', sym: 'kr' },
  { code: 'SGD', name: 'Singapore Dollar', sym: 'S$' },
  { code: 'SHP', name: 'Saint Helena Pound', sym: '£' },
  { code: 'SLE', name: 'Sierra Leonean Leone', sym: 'Le' },
  { code: 'SOS', name: 'Somali Shilling', sym: 'Sh' },
  { code: 'SRD', name: 'Surinamese Dollar', sym: '$' },
  { code: 'SSP', name: 'South Sudanese Pound', sym: '£' },
  { code: 'STN', name: 'São Tomé and Príncipe Dobra', sym: 'Db' },
  { code: 'SYP', name: 'Syrian Pound', sym: '£S' },
  { code: 'SZL', name: 'Eswatini Lilangeni', sym: 'E' },
  { code: 'THB', name: 'Thai Baht', sym: '฿' },
  { code: 'TJS', name: 'Tajikistani Somoni', sym: 'SM' },
  { code: 'TMT', name: 'Turkmenistani Manat', sym: 'm' },
  { code: 'TND', name: 'Tunisian Dinar', sym: 'د.ت' },
  { code: 'TOP', name: 'Tongan Paʻanga', sym: 'T$' },
  { code: 'TRY', name: 'Turkish Lira', sym: '₺' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', sym: 'TT$' },
  { code: 'TWD', name: 'New Taiwan Dollar', sym: 'NT$' },
  { code: 'TZS', name: 'Tanzanian Shilling', sym: 'TSh' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', sym: '₴' },
  { code: 'UGX', name: 'Ugandan Shilling', sym: 'USh' },
  { code: 'USD', name: 'US Dollar', sym: '$' },
  { code: 'UYU', name: 'Uruguayan Peso', sym: '$U' },
  { code: 'UZS', name: 'Uzbekistani Som', sym: 'soʻm' },
  { code: 'VES', name: 'Venezuelan Bolívar', sym: 'Bs.' },
  { code: 'VND', name: 'Vietnamese Đồng', sym: '₫' },
  { code: 'VUV', name: 'Vanuatu Vatu', sym: 'VT' },
  { code: 'WST', name: 'Samoan Tālā', sym: 'WS$' },
  { code: 'XAF', name: 'Central African CFA Franc', sym: 'FCFA' },
  { code: 'XCD', name: 'East Caribbean Dollar', sym: 'EC$' },
  { code: 'XOF', name: 'West African CFA Franc', sym: 'CFA' },
  { code: 'XPF', name: 'CFP Franc', sym: '₣' },
  { code: 'YER', name: 'Yemeni Rial', sym: '﷼' },
  { code: 'ZAR', name: 'South African Rand', sym: 'R' },
  { code: 'ZMW', name: 'Zambian Kwacha', sym: 'ZK' },
  { code: 'ZWG', name: 'Zimbabwe Gold', sym: 'ZiG' }
];

const byCode = new Map(CURRENCIES.map(c => [c.code, c]));

export const isCurrency = code => byCode.has(String(code || '').trim().toUpperCase());

// Substring search over code, name and symbol. Ranking: currencies from the
// sheet's Lists tab (commonCodes) first, then code-prefix matches, then rest.
export function searchCurrencies(q, commonCodes = []) {
  const t = String(q || '').trim().toLowerCase();
  const hits = !t ? [...CURRENCIES] : CURRENCIES.filter(c =>
    c.code.toLowerCase().includes(t) ||
    c.name.toLowerCase().includes(t) ||
    (c.sym && c.sym.toLowerCase().includes(t)));
  const rank = c =>
    (commonCodes.includes(c.code) ? 0 : 2) +
    (t && c.code.toLowerCase().startsWith(t) ? 0 : 1);
  return hits.sort((a, b) => rank(a) - rank(b) || a.code.localeCompare(b.code));
}
